name: Install PlayStation Mobile SDK
description: Installs the PlayStation Mobile SDK.
inputs:
    version:
      description: Target version
      required: false
      default: 2.00.00
runs:
    using: composite
    steps:
    - name: Install dependancies
      id: install-deps
      run: pip3 install psutil requests
      shell: pwsh
    - name: Run install script
      id: install-psm
      run: python3 ${{ github.action_path }}dist/install_psm.py ${{ inputs.version }}
      shell: pwsh
branding:
    icon: star
    color: green