name: Install PlayStation Mobile SDK
description: Installs the PlayStation Mobile SDK.
inputs:
    version:
      description: Target version
      required: false
      default: 2.00.00
runs:
    using: composite
    steps:
    - id: install-psm
      run: |
        pip3 install psutil requests
        python3 install_psm.py ${{ inputs.version }}
      shell: pwsh
branding:
    icon: star
    color: green